apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-wif-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generic-wif-example
  template:
    metadata:
      labels:
        app: generic-wif-example
    spec:
      serviceAccountName: generic-wif-app-sa
      volumes:
        # Define the CSI volume that will mount the GCP secrets
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: generic-wif-secrets
      containers:
        - name: app
          image: nginx:latest
          # Mount the secrets into the container
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi 