apiVersion: v1
kind: ServiceAccount
metadata:
  name: generic-wif-app-sa
  annotations:
    # If using GCP service account impersonation, configure it here
    iam.gke.io/gcp-service-account: prod-sa@my-prod-project.iam.gserviceaccount.com 