
serviceAccount:
  annotations: {}
  name: ""

extraArgs: []
logLevel: 0
image:
  repository: zondax/secrets-store-csi-driver-provider-gcp
  pullPolicy: IfNotPresent
  tag: ""

podAnnotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 64Mi

priorityClassName: ""

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}

adc:
  enabled: false
  path: /var/gcp
  keyName: gcp-sa-credential.json
  data: ""
